### ISSUE TITLE
Updates to Libraries

### ISSUE THREAD

**Issue by jazzyjester** [ribot/ribot-app-android#16]
Hey
Thanks for  a great app and architecture.

Do you plan to make updates to the boilerplate project ? 
(like RxJava, BuildTools, Google Services ,  etc)  ?

Thanks.

**Comment by jemmaSlater** [comment]
Why hello, and thank you!

Sadly, there are no current plans to make any changes to this project in the near future, and it is not being maintained or updated. 

Our most recently updated project is the boilerplate (https://github.com/ribot/android-boilerplate) and this is the project we hope to keep most up to date and will be returning to every now and then with updates.
