### ISSUE TITLE
App rotation on request

### ISSUE THREAD

**Issue by legarspol** [ribot/ribot-app-android#6]
Hi !
Just curious: Is it right that the app somehow forget that it sent a sign-in request if the user turn the screen of the device after pushing the button ? The http request get cancelled and loading sign get removed.

How is your way to handle this when the current state (loading) can barely get stored in DB ?

**Comment by ivacf** [comment]
Hi, it's definitely not ideal that the request gets cancelled on screen rotation however it's usually not a major problem for the user. This app doesn't handle that case. One possible way to achieve this would be to keep presenter instances across configuration changes so the same presenter instance can be re-attached to the new view.
